name = "HOROSCOPE_MODULE"
description = "Your daily horoscope"
version = "1.0.0"
github = "Nadybot/HOROSCOPE_MODULE"
author = "Nadyita"
bot_type = "Nadybot"
bot_version = "^7.0.0-alpha.1"

[requires]
ext-json = "*"
